#!/usr/bin/env bash

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# border/gap
bspc config border_width  1
bspc config window_gap    8

# split ratio
bspc config split_ratio 0.5

# focus
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# border colors
bspc config normal_border_color   "#15161e"
bspc config focused_border_color  "#7aa2f7"
bspc config active_border_color   "#7aa2f7"

# bar
pkill polybar
polybar &

# picom
pkill picom
picom &

# wallpaper
feh --bg-fill --randomize ~/.wallpapers/* &

# cursor
xsetroot -cursor_name left_ptr &

# redshift
pidof redshift || redshift &
